<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PH3A7DM" failures="1" tests="7" name="Test" time="91.943" errors="0" timestamp="2021-12-09T22:59:45 IST">
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="validatePageTitle" time="0.095"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="loginTest" time="10.024"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="verifyTitle" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [Cogmento CRM1] but found [Cogmento CRM]">
      <![CDATA[java.lang.AssertionError: expected [Cogmento CRM1] but found [Cogmento CRM]
at com.crm.qa.testcases.HomePageTest.verifyTitle(HomePageTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyTitle -->
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="verifyLable" time="0.085"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="serachfield" time="0.054"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="contactLink" time="4.316"/>
  <testcase classname="com.crm.qa.testcases.GitClass" name="test" time="0.0"/>
</testsuite> <!-- Test -->
